# ---- preset paras ---- (for test only)
test: True
suffix: # custom suffix for checkpoint name

# ----- adversary ---------
adversary: pgd # fgsm # trades
eps: 8
pgd_alpha: 2
pgd_iter: 10
alpha: 1.0  # interpolation between clean loss and ad loss # not supported for TRADES
rand_init: True
target: # Target attack

ad_test: pgd # fgsm
eps_test: 8
pgd_alpha_test: 2
pgd_iter_test: 10

# -- track per-instance learning info --- 
exTrack: True # would be slow for TRADES because have to generate ad examples twice, one for PGD-10

# -- subset training with specified indices --
train_subset_path: '/home/chengyu/RobustDataProfiling/data_subsets/id_friend_25000_balance.npy'

# ----- Regular paras ------
dataset: cifar10 # mnist
trainsize: # random subset
testsize:
data_dir: '/home/chengyu/RobustDataProfiling/data'
opt: sgd # adam
model: PreActResNet18 # wrn
bn: True # only valid for vgg
depth: 16  # only valid for wrn
width: 10 # only valid for wrn
scheduler: multistep
resume: False # resume training from a break point?
epochs: 5 # 160
milestones: [80, 120]
lr: 0.1 # 0.001 - adam
wd: 0.0005
momentum: 0.9
batch_size: 128
gamma: 0.1

gpu_id: 3
manualSeed: # 7 # specify random seed, leave blank if none
state_path: # pre-trained model
best: 'robust' # use robust accuracy to identify the best model during training
traintest: True # separate training subset for evaluation
save_model: False # True # Save the model after completing training?
save_interval: 0
