# ---- preset paras ---- (for config only)
test: False # True
suffix: # custom suffix for checkpoint name

# ----- adversary ---------
adversary: pgd # fgsm # trades # fat # mart # gairat
eps: 8
pgd_alpha: 2
pgd_iter: 10
alpha: 1.0  # interpolation between clean loss and ad loss
rand_init: True
fat_taus: [10, 0, 0] #  FAT setting
fat_milestones: [31, 61] # GAIRAT setting
target: # Target attack

ad_test: pgd # fgsm
eps_test: 8
pgd_alpha_test: 2
pgd_iter_test: 10

# -- track per-instance learning info --- 
exTrack: True # would be slow for TRADES because have to generate ad examples twice, one for PGD-10

# -- subset training with specified indices --
# train_subset_path: '/home/chengyu/Initialization/data_subsets/id_friend_25000_balance.npy'

# ----- Regular paras ------
dataset: cifar10 # mnist
trainsize: # random subset
testsize:
data_dir: '/home/chengyu/Initialization/data'
opt: sgd # adam
model: PreActResNet18 # logistic # resnet #_woskip # dln11 # vgg11 # dln11 # resnet_fixup # dln11 # resnet_woskip # vgg11 # logistic #  resnet # _woaffine # _wobn # vgg11 # _bn # resnet  #
bn: True
depth: 20 # 
width: 64
scheduler: multistep
resume: False
epochs: 160
milestones: [80, 120]
lr: 0.1 # 0.001 - adam
wd: 0.0005
momentum: 0.9
batch_size: 128
gamma: 0.1

gpu_id: 7
manualSeed: # 7
state_path: #  'sgd_resnet20_gain=1_0_ad_pgd_5_wd=0_0005_mom=0_9/model.pt'
best: 'robust'
traintest: True
save_model: False # True # Save the model after completing training?
save_interval: 0
